### PR TITLE
Created hitfarm.rb

### PR DESCRIPTION
**Pull request by Sitzilla**
# Internal Notes
@addamh Created hitfarm.rb to hit the hitpfarm/update endpoint for updating sentiment/spam/datarank values values for a comment..

# Release Notes
[enhancement] Created wrapper for updating sentiment/spam/datarank values for a comment.

### CODE REVIEW

**Comment by kennycason** [comment]
Administrative endpoints don't need to be part of the public sdk.

**Comment by Sitzilla** [comment]
@kennycason makes sense... I guess that would technically give anyone the ability to make these updates.  How can we set this up so that our internal team can still use it?

**Comment by addamh** [comment]
I thought this as well when you asked me but I went ahead and told you to go ahead cause I figured changing sentiment on comments is also a public/Customer facing feature. But, for what to do for private APIs is to maintain a fork of the sdk that is not public on github and include it in the gem file from source

**Comment by addamh** [comment]
Closing for the private extended sdk

**Pull request closed without merging**
